### ISSUE TITLE
Find out schematic diagram for CMU's robot.

### ISSUE THREAD

**Issue by okyspace** [DinoHub/devmgmt-monkeybotics#101]

**Comment by Blqe** [comment]
Next thursday 9pm

**Comment by timothymah** [comment]
Refer to schematic diagram provided by CMU here:
https://docs.google.com/presentation/d/1939mRyugkFX_UyE60eX0xnKeHbnxH7tTk7NVs7x2WZs/edit?usp=sharing

**Comment by jw5410** [comment]
Clarified - latching relay is for physical latching of drone onto UGV. Time-sync pulses sent from IMU to other sensors (to camera thru Teensy). 

However, we were introduced to new v2 UAV design comprising 6 cameras instead of lidar. Propose to close this issue and open new one if we need the new schematic diagram.
