### ISSUE TITLE
Manual generation of trajectories and images collection in UE4.

### ISSUE THREAD

**Issue by okyspace** [DinoHub/devmgmt-monkeybotics#32]
**Background:** To be able to manually generate trajectories within UE virtual environments to evaluate TartanVO performance, e.g. indoor flying, since TartanAir trajectory generation pipeline does not offer much flexibility in specifying trajectories.

Subtask as follows:
1. To re-run Tartanair on new dev laptop: In progress- current tartanair is down with a bug.
2. After collection of data + trajectory, follow trajectory with manual keyboard control.
3. Evaluate both results from trajectory from tartanair and trajectory from manual keyboard control with tartanvo to check viability of keyboard controls.

**Comment by Melvin-leo** [comment]
Completed

**Comment by Melvin-leo** [comment]
Rebuilt an image that uses the older tartanair version

**Comment by Melvin-leo** [comment]
Massive bug on data collection. Couple of tests ran on other environments. 

Firstly, even if flying very minimally(Aka flying straight). The ATE is not great.
Secondly, when testing simple flight path like straight then turning right, the graph showed that my ground truth is slightly inverted. I might need to ask Wen Shan on whether the graphs is wrong or on how the ground truths are collected.

Frequency is alright, 10-7hz, I have reduced the speed for testing. ATE is similar(not good). Might be due to the ground truth and tartanvo model thing. I will have to clarify with Wen Shan.

**Comment by Melvin-leo** [comment]
Tasks left

- [Incooperate into Tartanair Pipeline for step 2 onwards:(image collection done from tartanair)] 

- [ ] Package and upload to ZenHub as a repository

**Comment by Melvin-leo** [comment]
Created Repository for airsim keyboard control.
