### ISSUE TITLE
Single-drone stack (FUEL + FAST-LIO) in AirSim

### ISSUE THREAD

**Issue by okyspace** [DinoHub/devmgmt-monkeybotics#64]
To Close:
1. Get exploration-planning + SLAM stack ready for OR evaluation
2. Get exploration-planning + SLAM stack ready for porting to hardware
3. Learn to tune exploration-planning parameters for different envs

**Comment by jw5410** [comment]
Got FUEL running with lidar instead of depth camera, and learnt to change params to suit our sensor specs (range, FOV etc.). Need to dive deeper into all the params in algorithm.xml for FUEL to work effectively with our own setups.  ![image.png](https://images.zenhubusercontent.com/60decf83edddede6324e1e95/f3d64822-5a97-47a7-b82f-80e64b2de925)

Got AirSim to work with ArduCopter SITL. Need to use [ip addr show eth0] then set given ip addr in settings.json, before running SITL from ardupilot/ArduCopter folder with [sim_vehicle.py -v ArduCopter -f airsim-copter --console --map -A --sim-address=$WSL_HOST_IP]

**Comment by jw5410** [comment]
FUEL can now take /odometry and /lidar_points from AirSim and output /VelCmd to AirSim, so we now have a preliminary exploration planner working for AirSim. But it seems odometry heading is wrong and need to check if xyz axes are aligned between FUEL and AirSim. [image.png](https://images.zenhubusercontent.com/60decf83edddede6324e1e95/42329b23-85c-4224-ba9f-1b7900bffc51)

**Comment by jw5410** [comment]
Found that AirSim odom wasn't being used for subsequent path_planning (only initial point being used??), resulting in a growing deviation between drone position in airsim and where FUEL planner thinks the drone is (and therefore plans paths for). Will have to correct this deviation in code before we can continue. Also, understanding what the parameters do and being able to tune them appropriately will be a large task moving forward

**Comment by jonyktan** [comment]
Any branch that you worked on that we should fork to DinoHub?

@jw5410

**Comment by jw5410** [comment]
![image.png](https://images.zenhubusercontent.com/60decf83edddede6324e1e95/72217135-2611-4ac8-8714-e7d52879ebf7) hot-fixed the "odom wasn't being used for subsequent path-planning" issue, and the drone finally explores all of Building_99 in AirSim (altho it got stuck on glass wall right at the end)

@jonyktan yes, can share my branch for y'all to try! There's still a lot of code-cleanup and understanding of the algorithm parameters required, so any interest is welcome!
